language: java
jdk:
  - oraclejdk8
matrix:
  include:
    - os: linux
      env: DISPLAY=:99.0
    - os: osx
      osx_image: xcode9.3
cache:
  directories:
    - $HOME/.m2
before_install:
  - echo "MAVEN_OPTS='-Xmx1024m'" > ~/.mavenrc
install: true
before_script:
  - sh -e ./unix_display_server.sh
  - cd dk.sdu.mdsd.micro_lang.parent
script:
  - mvn -e clean install
after_failure:
  - cat dk.sdu.mdsd.micro_lang.ui.tests/target/work/data/.metadata/.log
