language: java
jdk:
  - oraclejdk8
os:
  - linux
  - osx
cache:
  directories:
    - $HOME/.m2
install: true
before_install:
  - echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc
script:
  - mvn clean install
