language: java
jdk:
  - oraclejdk8
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
cache:
  directories:
    - $HOME/.m2
install: true
before_install:
  - echo "MAVEN_OPTS='-Xmx1024m'" > ~/.mavenrc
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install java8; fi
script:
  - mvn clean install
