language: java
jdk:
  - oraclejdk8
matrix:
  include:
    - os: linux
      env: DISPLAY=:99.0
      before_script:
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
        - cd dk.sdu.mdsd.micro_lang.parent
    - os: osx
      osx_image: xcode9.3
cache:
  directories:
    - $HOME/.m2
before_install:
  - echo "MAVEN_OPTS='-Xmx1024m'" > ~/.mavenrc
before_script:
  - cd dk.sdu.mdsd.micro_lang.parent
script:
  - mvn -e clean install
after_failure:
  - cat dk.sdu.mdsd.micro_lang.ui.tests/target/work/data/.metadata/.log
