language: java
jdk:
  - oraclejdk8
os:
  - linux
  - osx
matrix:
  include:
    - os: osx
      osx_image: xcode9.3
cache:
  directories:
    - $HOME/.m2
install: true
before_install:
  - echo "MAVEN_OPTS='-Xmx1024m'" > ~/.mavenrc
script:
  - mvn clean install
